name: Terraform Provisioning

on:
  push:
    branches:
      - main
      - ouath_flow
      - terraform_step

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4



      - name: Create terraform.tfvars file
        run: |
          cat > terraform/terraform.tfvars <<EOF
          project_id             = "${{ secrets.GCP_PROJECT_ID }}"
          region                 = "${{ secrets.GCP_REGION }}"
          django_secret_key      = "${{ secrets.DJANGO_SECRET_KEY }}"
          google_client_id       = "${{ secrets.GOOGLE_CLIENT_ID }}"
          google_client_secret   = "${{ secrets.GOOGLE_CLIENT_SECRET }}"
          google_redirect_uri    = "${{ secrets.GOOGLE_REDIRECT_URI }}"
          EOF


      - name: Terraform Plan (debug)
        run: |
          export TF_LOG=DEBUG
          terraform plan -var-file="terraform.tfvars"
        working-directory: terraform


      - name: Write GCP credentials to file for Terraform
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > /tmp/account.json
        shell: bash

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
