name: Terraform Provisioning

on:
  push:
    branches:
      - main
      - ouath_flow
      - terraform_step

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Create terraform.tfvars file
        run: |
          cat > terraform/terraform.tfvars <<EOF
          project_id          = "${{ secrets.GCP_PROJECT_ID }}"
          region              = "us-central1"
          django_secret_key   = "${{ secrets.DJANGO_SECRET_KEY }}"
          oauth_client_id     = "${{ secrets.OAUTH_CLIENT_ID }}"
          oauth_client_secret = "${{ secrets.OAUTH_CLIENT_SECRET }}"
          EOF

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: terraform
